### ISSUE TITLE
Complete documentation of dataset

### ISSUE THREAD

**Issue by larnsce** [openwashdata/chckapmalawi#2]
This would be next in line in terms of priority, but also tidyness of data. 

This time I have a good and response contact that could support you to identify descriptions for variables.

In #1 we have the ORCID iDs also of the enumerators.

**Comment by sskorik01** [comment]
Yes, can you provide me the original excel? It's not in the data-raw folder, and I cannot find it in the data repository either. Thanks!

**Comment by larnsce** [comment]
Yes, it's still in gitignore because it contains some variables with sensitive information. Will share it with you in a different way.

**Comment by larnsce** [comment]
Sent you the original email

**Comment by sskorik01** [comment]
I'm getting the following error when running pkgdown::build_site(): 

pkgdown::build_site()
-- Installing package into temporary library ----------------------------------------------------------------------------------------------------
== Building pkgdown site =======================================================
Reading from: 'C:/Users/sskorik/Documents/gitrepos/chckapmalawi'
Writing to:   'C:/Users/sskorik/Documents/gitrepos/chckapmalawi/docs'
-- Initialising site -----------------------------------------------------------
-- Building home ---------------------------------------------------------------
Reading 'LICENSE.md'
Error: 
! in callr subprocess.
Caused by error in `purrr::map2(components, names(components), data_home_component, …`:
! In index: 1.
ℹ See `$stdout` for standard output.
Type .Last.error to see the more details.

Do you have an idea what it is due to?

**Comment by mianzg** [comment]
> I'm getting the following error when running pkgdown::build_site():
> 
> pkgdown::build_site() -- Installing package into temporary library ---------------------------------------------------------------------------------------------------- == Building pkgdown site ======================================================= Reading from: 'C:/Users/sskorik/Documents/gitrepos/chckapmalawi' Writing to: 'C:/Users/sskorik/Documents/gitrepos/chckapmalawi/docs' -- Initialising site ----------------------------------------------------------- -- Building home --------------------------------------------------------------- Reading 'LICENSE.md' Error: ! in callr subprocess. Caused by error in `purrr::map2(components, names(components), data_home_component, …`: ! In index: 1. ℹ See `$stdout` for standard output. Type .Last.error to see the more details.
> 
> Do you have an idea what it is due to?

@sskorik01 See my comment for `cleanteamghana`: https://github.com/openwashdata/cleanteamghana/issues/2#issuecomment-1882846879

**Comment by larnsce** [comment]
@sskorik01: Do you still have this error after following @mianzg's guidance?

**Comment by sskorik01** [comment]
Yes, it is all resolved now!
